version: "3"

services:

    lampC:
      # use either tag "latest" or any other version like "6.5.3.0", ...
      image: lamp-stack
      container_name: lampC
      ports:
         - "8080:80"
         - "3307:3306"
         #- "22:22"
         #- "8888:8888"
         #- "9999:9999"
      volumes:
         - "lamp_db_volume:/var/lib/mysql"
         - ./src:/var/www/html
         #- "lamp_site_volume:/var/www/html"
                 
      networks:
         - web
      environment:
         # default = 0, recommended to be OFF for frontend devs
         #- XDEBUG_ENABLED=1
         # default = latest PHP, optional = specific version
         #- PHP_VERSION=8.1
         - MYSQL_ROOT_PASSWORD=root
      #extra_hosts:
       # - "docker.shopware.dev:127.0.0.1"     

volumes:
  lamp_db_volume:
    driver: local
  #lamp_site_volume:
    #driver: local
  
networks:
  web:
    external: false